# Generated by Django 5.2 on 2025-05-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion',
            name='emotion',
            field=models.CharField(max_length=10),
        ),
    ]
