# Generated by Django 5.2 on 2025-05-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion', '0002_alter_emotion_emotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotion',
            name='marking',
            field=models.BooleanField(default=False),
        ),
    ]
