# Generated by Django 5.2 on 2025-05-07 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emotion', '0003_emotion_marking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emotion',
            name='marking',
        ),
    ]
