# Generated by Django 5.2 on 2025-05-07 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emotion', '0002_alter_emotion_emotion'),
        ('people', '0002_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='diary/audio/')),
                ('emotion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emotion.emotion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.people')),
            ],
        ),
    ]
