# Generated by Django 5.2 on 2025-05-23 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diary', '0001_initial'),
        ('emotion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='emotion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emotion.emotion'),
        ),
    ]
