# Generated by Django 5.2 on 2025-05-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_diary_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='marking',
            field=models.BooleanField(default=False),
        ),
    ]
