# Generated by Django 5.2 on 2025-05-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_diary_marking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
