# Generated by Django 5.2 on 2025-05-23 07:24

from django.db import migrations, models
import django.contrib.postgres.fields

class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_initial'),
    ]

    operations = [
        # 1) 기존 emotion 컬럼 제거
        migrations.RemoveField(
            model_name='diary',
            name='emotion',
        ),
        # 2) ArrayField 로 새 emotion 컬럼 추가
        migrations.AddField(
            model_name='diary',
            name='emotion',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(),
                size=7,
                default=list,
                help_text='7가지 감정 비율 리스트',
                verbose_name='감정 비율',
            ),
        ),
    ]
