# Generated by Django 5.2 on 2025-05-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_alter_diary_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='audio',
            field=models.FileField(null=True, upload_to='diary/audio/'),
        ),
    ]
