# Generated by Django 5.2 on 2025-06-09 14:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_alter_diary_emotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='emotion',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, help_text='[행복, 슬픔, 놀람, 화남, 혐오, 공포] 순서로 0~1 사이의 확률 리스트', size=6, verbose_name='감정 비율'),
        ),
    ]
