# Generated by Django 5.2 on 2025-05-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_alter_diary_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
