# Generated by Django 5.2 on 2025-05-31 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharing',
            name='share_state',
            field=models.CharField(choices=[('unmatched', '연동 대기'), ('matched', '연동 완료'), ('regected', '연동 거절')], default='unmatched', max_length=10),
        ),
    ]
