# Generated by Django 5.2 on 2025-05-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='user_type',
            field=models.CharField(default='default', max_length=10),
        ),
    ]
