# Generated by Django 5.2 on 2025-06-02 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_alter_sharing_share_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharing',
            name='relation',
        ),
    ]
