# Generated by Django 5.2 on 2025-06-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_remove_sharing_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharing',
            name='share_range',
            field=models.CharField(choices=[('partial', '부분 공개'), ('full', '전체 공개')], default='partial', max_length=10),
        ),
    ]
