# Generated by Django 5.2 on 2025-05-14 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_sharing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharing',
            name='relation',
        ),
        migrations.AddField(
            model_name='people',
            name='user_id',
            field=models.CharField(default='default', max_length=30),
        ),
        migrations.AddField(
            model_name='sharing',
            name='share_state',
            field=models.CharField(choices=[('unmatched', '연동 대기'), ('matched', '연동 완료')], default='unmatched', max_length=10),
        ),
        migrations.AlterField(
            model_name='people',
            name='user_type',
            field=models.CharField(choices=[('user', '일반 사용자'), ('guardian', '보호자')], default='user', max_length=10),
        ),
        migrations.AlterField(
            model_name='sharing',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sharing',
            name='share_range',
            field=models.CharField(choices=[('private', '비공개'), ('partial', '부분 공개'), ('full', '전체 공개')], default='private', max_length=10),
        ),
        migrations.AlterField(
            model_name='sharing',
            name='shared_with',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_shares', to='people.people'),
        ),
    ]
