# Generated by Django 5.2 on 2025-05-14 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_remove_sharing_relation_people_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='user_id',
            new_name='string_id',
        ),
    ]
