# Generated by Django 5.2 on 2025-05-16 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_sharing_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='string_id',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
